run: test.cpp the1.cpp
	g++ test.cpp the1.cpp -Wall -std=c++11 -o test
	./test

run2: test2.cpp the1.cpp
	g++ test2.cpp the1.cpp -Wall -std=c++11 -o test
	./test

run3: test3.cpp the1.cpp
	g++ test3.cpp the1.cpp -Wall -std=c++11 -o test
	./test
